apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: nasi101/notification
          resources:                # Add the resources section here
            requests:
              memory: "128Mi"       # Minimum memory the pod requests
              cpu: "250m"           # Minimum CPU the pod requests
            limits:
              memory: "256Mi"       # Maximum memory the pod can use
              cpu: "500m"           # Maximum CPU the pod can use
          envFrom:
            - configMapRef:
                name: notification-configmap
            - secretRef:
                name: notification-secret
